SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

METEOR_MIN_RADIUS = 20
METEOR_KINDS = 3
METEOR_SPAWN_RATE = 0.8  # seconds
METEOR_MAX_RADIUS = METEOR_MIN_RADIUS * METEOR_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
